name: T&T Enterprise CI Suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job 1: Check the Auth Service
  auth-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Auth Deps
        run: |
          cd auth-service
          pip install -r requirements.txt
      - name: Lint Auth Service
        run: |
          pip install flake8
          flake8 auth-service --count --select=E9,F63,F7,F82 --show-source --statistics

  # Job 2: Check the Attendance Service
  attendance-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Attendance Deps
        run: |
          cd attendance-service
          pip install -r requirements.txt
      - name: Lint Attendance Service
        run: |
          pip install flake8
          flake8 attendance-service --count --select=E9,F63,F7,F82 --show-source --statistics